### ISSUE TITLE
getpublicidbynickname?nickname=ĘŚĆ

### ISSUE THREAD

**Issue by vaseker** [PhpSurvarium/SurvariumAPI#1]
Как правильно экранировать никнеймы игроков? PID для `ĘŚĆ` не получить.

`http://api.survarium.com/getpublicidbynickname?nickname=%C4%98%C5%9A%C4%86`

**Comment by vaseker** [comment]
Невозможно получить **верный** PID игрока по нику, содержащему смесь англо-русских символов:
- Buba (`а` русская) выдает Buba (все на латинице).
- слепой (`o` английская) выдает не того слепого

И так далее.

**Comment by vaseker** [comment]
Теперь есть `paids` с синонимами. Спасибо!
Отсюда следующий вопрос: какая сортировка в этом хэше?
По релевантности, дате регистрации, и т.д.

**Comment by PhpSurvarium** [comment]
Сортировка по никнеймам от меньшего к большему. 
Подробней: http://php.net/manual/en/function.ksort.php
