### ISSUE TITLE
Данные профиля с сайта

### ISSUE THREAD

**Issue by Jemixs** [PhpSurvarium/SurvariumAPI#10]
Можно ли получить данные профиля игрока с оф. сайта игры? 
Например дату регистрации? Или его аватар на сайте?

**Comment by PhpSurvarium** [comment]
В будущем, возможно, будет добавлен функционал, позволяющий,
получить информацию о пользователях, 
которая есть в открытом доступе.
На данный момент это не приоритетная задача.
