### ISSUE TITLE
Проблема с использованием getNewMatches

### ISSUE THREAD

**Issue by aaa4xu** [PhpSurvarium/SurvariumAPI#11]
При отсутствии новых матчей после переданного ему timestamp отдает 422 статус

**Comment by vaseker** [comment]
422, похоже, здесь стандартный код пустого ответа. 
http://api.survarium.com/getclaninfo?clanid=51829 тут тоже 422

Хотя 422 странный [выбор кода](https://ru.wikipedia.org/wiki/Список_кодов_состояния_HTTP#422), да.

**Comment by PhpSurvarium** [comment]
Добавил, параметр "count" с количеством матчей (лимит 50),
при отсутствии новых матчей возращает  пустой ключ "matches".
Проверить можно будет после перезда на новый сервер, возможно (29.12).

Могу в тело ответа отдавать json с кодом и описанием ошибки. 
Высказывайте более конкретные пожелания, по этому поводу.

**Comment by vaseker** [comment]
Да, в теле ответа хотелось бы иметь описание ошибки.
Возможно даже задекларировать ошибки, например, в вики.

**Comment by PhpSurvarium** [comment]
Ошибки, добавлю.

**Comment by vaseker** [comment]
Метод перестал отдавать данные после
3859764 | 2016-01-26 14:30:00

UPD: видать, просто вырубили выгрузку данных в api, так как нет 3859765, 3859766 и так далее.

**Comment by PhpSurvarium** [comment]
Исправлено

**Comment by vaseker** [comment]
API отдает **только** клановые матчи.

**Comment by vaseker** [comment]
Вопрос к пагинации ответа: если будет ответ с матчами, имеющими таймштампы (count=5)
- 123
- 1234
- 1234
- 1234
- 1234

то, запросив getNewMatches?timestamp=1234, в ответе должны быть матчи с таймштампом 1234, или с таймштампом больше 1234?
А еще, таймштамп точно указывает на дату создания матча в апи, а не на дату боя? Кажется, я ловлю кейсы, что часть матчей импортируются "задним числом", из-за чего такие матчи не могут быть извлечены из getNewMatches, либо это кейс, что getNewMatches отдает 100500 матчей с одинаковым таймштампом, однако добавление offset делает +1 к timestamp и пропускается уйма матчей.

**Comment by vaseker** [comment]
API отдавало новые матчи недолго: вечером того же дня API снова замолчало. Сейчас нет новых матчей.

**Comment by PhpSurvarium** [comment]
$timestamp в данном запросе обозначанет время добавления матча в статистику API, что может в силу различных обстоятельств отличаться от времени окончания матча.
Запрос возращает $limit матчей, время добавления которых в статитистику равно или больше $timestamp. Матчи сортируются по возрастанию timestamp, при одинаковом timestamp они сортируются по возрастанию match_id.
