### ISSUE TITLE
Отсутствие расширенной статистики матча у некоторых игроков

### ISSUE THREAD

**Issue by aaa4xu** [PhpSurvarium/SurvariumAPI#13]
Пример:

```
"10": {
    "pid": "13754228249027035675",
    "kill": "8",
    "die": "6",
    "victory": "0",
    "score": "100"
  },
  "13": {
    "pid": "513353363610890157",
    "kill": "29",
    "die": "11",
    "victory": "0",
    "score": "430",
    "headshot_kill": "3",
    "grenade_kill": "0",
    "melee_kill": "0",
    "artefact_kill": "0",
    "capture_a_point": "3",
    "bring_a_box": "0",
    "use_artefact": "6"
  }
```

Что это: просто ошибка в работе api или странное поведение, когда все дополнительные параметры равны 0?

**Comment by vaseker** [comment]
Судя по реплеям, это 0 в дополнительных параметрах.

**Comment by PhpSurvarium** [comment]
Эта информация доступна только c матча № 3096798,
ранее все значения 0.
В более новых матчах, если пользователь не совершил хотя бы одного из дополнительных действий, у него они не отображались, сейчас исправлено, везде должен быть 0.

**Comment by vaseker** [comment]
> Эта информация доступна только c матча № 3096798

Стоит упомянуть об этом в вики. Также было бы интересно узнать номер первого матча, доступного в api. Самый давний, что удалось найти - 2253112.

**Comment by vaseker** [comment]
В свежих данных очень часто появляются 0 в статистике действий.

**Comment by vaseker** [comment]
Нет статистики kill/die в матчах около 3 января, например: `3680580`

**Comment by aaa4xu** [comment]
"по статистике матчей за праздники к сожалению все плохо... удалены безвозвратно"

**Comment by PhpSurvarium** [comment]
Данные по убийстам и смертям за праздники к сожалению удалены.
