### ISSUE TITLE
No ammunition

### ISSUE THREAD

**Issue by vaseker** [PhpSurvarium/SurvariumAPI#15]
Очень часто не приходит снаряжение из метода `getUserData`. Такое бывает при просмотре информации об игроках, как давно не игравших, так и по постоянно играющим.

> getUserData/?pid=18204466004326604361

``` json
{ "ammunition": false }
```

**Comment by PhpSurvarium** [comment]
При выходе патча, у персонажа автоматически из профелей все вещи перекладываются в инвентарь. Такая ситуация будет при выходе каждого патча.

**Comment by vaseker** [comment]
Понятное поведение. Как насчет описания этого в wiki?

**Comment by PhpSurvarium** [comment]
Обязательно
