### ISSUE TITLE
HTTP: 429

### ISSUE THREAD

**Issue by vaseker** [PhpSurvarium/SurvariumAPI#16]
Какой порог частоты обращений к api?

**Comment by PhpSurvarium** [comment]
Сейчас ограничение 5 запросов в секунду. 
В дальнейшем может быть измененено.

**Comment by vaseker** [comment]
Я понаписал итогов в wiki:
https://github.com/PhpSurvarium/SurvariumAPI/wiki

**Comment by PhpSurvarium** [comment]
Спасибо.
После Нового года более детально wiki опишу.

**Comment by vaseker** [comment]
Возможно ли временно снять данное ограничение? Получается, что запросы в апи должны приходить с минимальным интервалом в 200мс, однако на деле же апи банит при такой частотности обращений (при том, что еще включается задержка по сети около 100мс).

Опытным путем было выявлено, что задержка 400-600мс более оптимальна, но иногда и такая частотность попадает в бан. Итого пришлось задрать задержку до 800мс.

Сейчас у меня написаны импортеры данных, использующие очереди матчей из getNewMatches. Каждый новый матч импортируется последовательно, внутри каждого матча идет последовательное обращение (с указанной задержкой) к:
- getMatchStatistic
- getUserData (x10) –> getClanInfo (при наличии клана, и тут подложен 5 минутный кэш)

Таким образом, на каждый матч может выполниться серия последовательных запросов 800мс \* (1 + 10 + 10) = 16800мс (16.8 сек). В итоге получается, что импорт миллиона матчей может занять до 2х дней (во время разработки вообще каким-то образом насчитал 28 дней), за которые может случиться невесть что. Такие ограничения подходят для инкрементального импорта, однако совершенно не годятся для создания первого дампа.

Возможно ли временно снять ограничение, либо увеличить лимит хотя бы до 50RPS? Хочется выполнить импорт параллельными сериями по 30 матчей.

![2015-12-30 13-04-55 1 debug importer listen 3010 v1 true node server node](https://cloud.githubusercontent.com/assets/1942271/12047961/074d66a4-aef6-11e5-8294-ee35653b76f2.png)

**Comment by aaa4xu** [comment]
Ты что-то делаешь не так... Отправляю запросы асинхронно по 5 в секунду, 429 ошибка - редкость. Получение матча + всех игроков + всех кланов (1+14+14 = 29 запросов) занимает ~5,4сек.
![image](http://take.ms/Co2TP)

**Comment by vaseker** [comment]
@aaa4xu, ок, спасибо, займусь рефакторингом

**Comment by vaseker** [comment]
В общем, тоже добрался 5 секунд, однако это все еще очень долго.

**Comment by vaseker** [comment]
Получается импорт данных одного игрового дня занимает один реальный день. Можно, все-таки, увеличить лимит на количество запросов в секунду?

**Comment by PhpSurvarium** [comment]
Для тестирования лимит временно отключен.
Если сервер не будет справлять, по мере необходимости, будем воодить ограничения.

**Comment by vaseker** [comment]
Спасибо!

**Comment by PhpSurvarium** [comment]
Ставлю временное ограничеие 20 rps

**Comment by vaseker** [comment]
Как-то странно отрабатывает ограничение. Выполняю запросы сильно медленнее лимита, но все равно попадаю в бан, плюс постоянно валятся ECONNRESET, ETIMEDOUT.

**Comment by PhpSurvarium** [comment]
Необходимая минимальная задержка между запросами 20 мс.

**Comment by vaseker** [comment]
Даже при секундной задержке получаю бан.

**Comment by PhpSurvarium** [comment]
Бан сегодня был отключен.
Проблема в данный момент еще актуальна?

**Comment by vaseker** [comment]
Без банов еще жить можно. Заработало.

**Comment by vaseker** [comment]
Задержка в между запросами в 20мс еще актуальна?
Сейчас 429 сыпется даже при 500мс.

**Comment by PhpSurvarium** [comment]
Актуальна.

**Comment by vaseker** [comment]
Для демонстрации сделал лог запросов с таймингами.
Запросы стартуют последовательно, с задержкой в 20мс. При ошибках 429, 5xx, и сетевых, происходит планирование повтора с задеркой 20 + [№ повтора] \* 400 \* [0..1 рандомное десятичное]мс.
https://travis-ci.org/survarium/survarium-api-client/builds/101863253, в самом низу лога, с голубыми идентификаторами (голубые таймеры - diff времени между сообщениями). 
По логу видно, что между запросами **всегда** не менее 20мс, но все равно прилетает 429.

Есть идеи, что не так?
