### ISSUE TITLE
Production/testing env

### ISSUE THREAD

**Issue by vaseker** [PhpSurvarium/SurvariumAPI#18]
Возможно ли поднятие публичного api в различных окружениях?
- production – stable версия, с минимальным количеством 5хх ошибок
- testing – версия с новым функционалом, с 5хх (то есть, текущий api.survarium.com)

**Comment by vaseker** [comment]
Словил в проде ошибку, присоединенную к JSON (брал информацию о клане 92)

**Comment by PhpSurvarium** [comment]
Код ошибки убрал из коммента,
над версиями подумаю.

**Comment by PhpSurvarium** [comment]
production - api.survarium.com
testing - apitest.survarium.com
