### ISSUE TITLE
500 getmatchstatisticbyid?matchid=*

### ISSUE THREAD

**Issue by vaseker** [PhpSurvarium/SurvariumAPI#2]
Привет! С вечера пятницы сломалась ручка получения статистики матчей.  
Пример запроса:

> http://api.survarium.com/getmatchstatisticbyid?matchid=3583902&language=russian

Пример ответа:

> exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access

**Comment by PhpSurvarium** [comment]
Исправлено
