### ISSUE TITLE
getNewMatches

### ISSUE THREAD

**Issue by vaseker** [PhpSurvarium/SurvariumAPI#21]
В методе нужна пагинация, либо поддержка параметра выдачи матчей по их дате старта, а не импорта. Сейчас получилось, что метод отдает 74520 матчей с одним и тем же таймштампом импорта с лимитом в  50 записей. Соответственно, из метода возможно получить только 50 из 74520 записей.

**Comment by PhpSurvarium** [comment]
Сегодня добавлю

**Comment by PhpSurvarium** [comment]
Добавил параметр offset.
В случае одинакого timestamp, матчи сортируются по возрастанию match_id
