### ISSUE TITLE
Профили предметов в getuserdatabypid

### ISSUE THREAD

**Issue by aaa4xu** [PhpSurvarium/SurvariumAPI#22]
1) На данный момент флаг active означает, что именно на эту вкладку игрок смотрит в игровом клиенте. Есть ли возможность изменить его логику (или добавить дополнительный флаг), который отражал бы "включенность" профиля?
2) Порядок профилей в API не всегда совпадает с порядком профилей в клиенте. Во время тестов, отключенный первый профиль в API отображался третьим
3) Хотелось бы получать названия профилей

**Comment by Kn9zev** [comment]
Поддерживаю.
И ещё, если у игрока заканчивается премиум-аккаунт, то отображается 3 профиля экипировки, а по идее должно быть 2.

**Comment by PhpSurvarium** [comment]
1. Третий профиль экипировки отключается только если заканчивается премиум аккаунт. Теперь отключенный профиль не отображается в статистике.
2. Добавил сортировку, теперь ключи 1, 2 и 3 обозначают соответствующие профиля.
3. Названия профилей - конфиденциальная информация пользователей.
