### ISSUE TITLE
Сломан метод getNicknamesByPublicIds

### ISSUE THREAD

**Issue by vaseker** [PhpSurvarium/SurvariumAPI#26]
Метод возвращает 0 и код 200
`print_r($api->getNicknamesByPublicIds(['17083592333428139024', '7542784095223883934']));`

> Array(
>     [code] => 200
>     [data] => 0
> )

**Comment by PhpSurvarium** [comment]
Спасибо,
исправлено.

**Comment by vaseker** [comment]
Теперь ок, тесты прошли. 
Рекомендую гонять тесты "на стороне" с некоей периодичностью. Например, https://travis-ci.org/survarium/survarium-api-client выполняются не реже раза в сутки, и вопят в случае ошибок.
