### ISSUE TITLE
Признак CW, дата основания клана

### ISSUE THREAD

**Issue by vaseker** [PhpSurvarium/SurvariumAPI#27]
Возможно ли добавить в матч информацию о том, является ли он клановым?
Также возможно ли добавить информацию и дате основания клана?
Спасибо.

**Comment by PhpSurvarium** [comment]
Да, добавлю в ближайшее время.

**Comment by PhpSurvarium** [comment]
В запрос getClanInfo($clanId) добавлен параметр 'creation_time' - дата создания.

В запрос getMatchStatistic($matchId) добавлен параметр 'is_clan' => [0|1].
Если 'is_clan'  => 1, добавляется параметр 'clan_match' : 
Пример:
'is_clan'  => 1,
'clan_match' => [
   0 => 1580,  // clan1_id
   1 => 3101  // clan2_id
]

**Comment by vaseker** [comment]
Спасибо!

**Comment by vaseker** [comment]
В клан-матче `3797575` баг: 

``` js
"clan_match": {
  "0": "14",
  "1": "30"
}
```

хотя реально участвовали кланы `23` и `263`.  
Клан `30` вообще отдает 422 ошибку.

Такая же проблема в матче посвежее: `3838524`, то есть, проблема глобального характера.

UPD: похоже, проблема относится к матчам до 23 января.

**Comment by vaseker** [comment]
Проблема постоянная. В свежем матче `3854904` кланы в `clan_match` не соответствуют кланам участников.

**Comment by PhpSurvarium** [comment]
Завтра приму меры.

**Comment by vaseker** [comment]
Есть новости относительно бага?

**Comment by PhpSurvarium** [comment]
Нет, исправим.
Сразу напишу.

**Comment by PhpSurvarium** [comment]
Исправлено
