### ISSUE TITLE
Публичные статусы

### ISSUE THREAD

**Issue by vaseker** [PhpSurvarium/SurvariumAPI#29]
Комплексный таск.
Возможно ли реализовать публикацию игроками и кланами статусов, которые можно было бы забирать из api?

В отсутствии возможности выдачи токенов пользователей сторонним разработчикам, публикация статусов позволила бы реализовать идентификацию пользователей, как это сейчас сделано на svfan.ru, который слушает игровой чат в ожидании шаблонных сообщений.

**Comment by PhpSurvarium** [comment]
Публикация статусов возможна в будущем,
в ближайшее время добавление этого функционала не планируется.
