### ISSUE TITLE
Несовпадение статистик

### ISSUE THREAD

**Issue by vaseker** [PhpSurvarium/SurvariumAPI#31]
Сообщают о кейсах, когда в игре итоговый счет один, а апи отдает другой. Это баг или фича?
Примеры: 
- `3873727`: [Piksel_IT](https://pp.vk.me/c629511/v629511393/38b4e/wocJtY0m0Mk.jpg), 43:3, в апи 43:2
- `3888059`: [Piksel_IT](https://pp.vk.me/c629530/v629530393/29672/zIY1YXWFfFE.jpg), 37:14, в апи 37:13

**Comment by vaseker** [comment]
Свежий матч с расхождением: `3926561`, [Vaseker](https://pp.vk.me/c629405/v629405166/35dec/lVR-vup0JDQ.jpg), 6:9, в апи 6:4.
Был тимкилл-эксперимент: меня убивали обычным расстрелом, взрывчаткой, хэдшотами и врукопашку и т.д. В итоге 5 смертей нет в статистике.

**Comment by vaseker** [comment]
Свежий матч от 10 февраля: `3970303`, игрок `1184448509909185632`. При счете 470, кд 3:2. Сам игрок говорит, что это неправда, и настреляно намного больше. У этого игрока это не единственный проблемный матч. Следующие такие же.
- `3970758`: [бурундук](https://pp.vk.me/c627428/v627428099/3235e/SBR3zt426NA.jpg), 16:8, в API 1:2

**Comment by PhpSurvarium** [comment]
Данные по количеству убийств и смертей в матчах исправлены.
Необходимо повторно запросить статистику матчей с 18:00 10.02.16 по 13:00 11.10.16 +2:00 GTM.
