### ISSUE TITLE
getNewMatches sort

### ISSUE THREAD

**Issue by vaseker** [PhpSurvarium/SurvariumAPI#35]
Метод не гарантирует сортировку элементов по таймштампу добавления матча. (https://github.com/PhpSurvarium/SurvariumAPI/issues/11#issuecomment-191266693)
Сортировка выполняется по id матча.

Пример: getNewMatches?timestamp=1458148590&limit=50

``` json
"4304758": "1458148861",
"4304771": "1458148741"
```

``` json
"4304681": "1458148621",
"4304682": "1458148741",
"4304683": "1458148621"
```

**Comment by vaseker** [comment]
При сортировке по ID, и выбирая из выдачи максимальный таймштамп, возможно на следующих страницах НЕ найти матч, если его ID больше, чем любой со страницы 1, но таймштамп меньше максимального значения.

**Comment by PhpSurvarium** [comment]
Матчи сортируются по возрастанию timestamp, при одинаковом timestamp они сортируются по возрастанию match_id.
