### ISSUE TITLE
Некорректный подсчет убийств прикладом

### ISSUE THREAD

**Issue by vaseker** [PhpSurvarium/SurvariumAPI#43]
Матч `4731965`
Игрок `16359211450428874103 (Славяна - БанЧата)`

> сделал 33 килла прикладом - написано 0

**Comment by phx00** [comment]
Исправлена ошибка из-за которой, при headshot_kill = 0,  отдавались неправильные значения: melee_kill, grenade_kill, artefact_kill, capture_a_point, bring_a_box, use_artefact

**Comment by vaseker** [comment]
Спасибо.
