### ISSUE TITLE
Прокачка умений игрока

### ISSUE THREAD

**Issue by aaa4xu** [PhpSurvarium/SurvariumAPI#7]
Хотелось бы получить доступ к умениям игрока через API. Есть ли такая возможность?

**Comment by PhpSurvarium** [comment]
Добавил метод SurvariumApi::getUserSkills($pid). 
Сервер возращает массив, содержащий [skill_id => skill_level],
если скилы отсутствуют сервер вернет пустой массив.

**Comment by vaseker** [comment]
Возможно ли получить словарь умений?
