### ISSUE TITLE
Bang in claninfo

### ISSUE THREAD

**Issue by vaseker** [PhpSurvarium/SurvariumAPI#8]
После добавления  ид  клана  к информации об игроке,  возможны ситуации,  когда попытка получить информацию о клане с таким ид, заканчивается пустым ответом. Например http://api.survarium.com/getclaninfo?clanid=51829

Как это интерпретировать? Случаи далеко не единичные.

**Comment by PhpSurvarium** [comment]
Эта ситуация возникала, когда клан еще не оплачен.
Добавил проверку на существование клана.

**Comment by vaseker** [comment]
Спасибо.
